version: '3.8'
services:
  road-safety-postgres: # Renamed from 'db' to match the extends directive
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accidents_db

    ports:
      - "5888:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
